### ISSUE TITLE
Transient failure in AnnouncerTest testSanity

### ISSUE THREAD

**Issue by fjy** [druid-io/druid#2451] opened 2016-02-11 18:22 UTC
testSanity(io.druid.curator.announcement.AnnouncerTest)  Time elapsed: 61.107 sec  <<< ERROR!
java.lang.Exception: test timed out after 60000 milliseconds
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedNanos(AbstractQueuedSynchronizer.java:1037)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1328)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:277)
	at org.apache.curator.test.Timing.awaitLatch(Timing.java:120)
	at io.druid.curator.announcement.AnnouncerTest.testSanity(AnnouncerTest.java:101)

**Comment by gianm** [comment] 2016-03-25 19:24
duplicate of https://github.com/druid-io/druid/issues/2253

**Closed by gianm** 2016-03-25 19:24 UTC
Labels: Testing
