### ISSUE TITLE
Mapping a single Kafka message to multiple Druid rows

### ISSUE THREAD

**Issue by JithinThomas** [druid-io/druid#4685] opened 2017-08-11 21:50 UTC
I've been using Druid to ingest data from Kafka. The messages in Kafka are thrift-serialized versions of custom records. In order to parse these serialized messages, I've written a custom Druid extension, which extends the ByteBufferInputRowParser class in Druid.

This has been working fine. However, one issue I've encountered is that the parse(T input) method of  ByteBufferInputRowParser lets me convert one input to only on Druid row. I

**Question:**
Is there a way for me to map a given input into multiple InputRow objects? Each of my Kafka messages has a list of items and I need to store each item as a separate Druid row.

**Comment by gianm** [comment] 2017-08-14 18:26
It's not currently possible. See #4373 for a proposal around making it possible.

Closing this since it's a duplicate of #4373.

**Closed by gianm** 2017-08-14 18:26 UTC
