### ISSUE TITLE
Backward incompatible change with Tranquility

### ISSUE THREAD

**Issue by niketh** [druid-io/druid#4095] opened 2017-03-22 16:45 UTC
@gianm @cheddar 

https://github.com/druid-io/druid/pull/4060 is causing a backward incompatible change which is breaking existing Tranquility, here is the error
`2017-03-22 14:02:06.527 y.s.a.s.DruidBeamSink TranquilitySink_[5 5] [ERROR] TranquilitySink - Problem preparing DruidBeam bolt in worker 5: java.lang.RuntimeException: org.codehaus.jackson.map.exc.UnrecognizedPropertyException: Unrecognized field "enabled" (Class org.apache.shaded.curator.x.discovery.ServiceInstance), not marked as ignorable
 at [Source: [B@1913fa09; line: 1, column: 234] (through reference chain: org.apache.shaded.curator.x.discovery.ServiceInstance["enabled"])``

**Comment by gianm** [comment] 2017-03-22 17:20
That looks like we need to set the "ignore unrecognized property" flag on whatever object mapper Tranquility is using, so probably a Tranquility bug rather than Druid bug.

What's the nature of the incompatibility exactly? Do you get that error when you run latest Tranquility against a Druid 0.10.0-rc1 cluster?

**Comment by niketh** [comment] 2017-03-22 17:46
@gianm We are using 0.5.0 version tranquility against a Druid latest (master branch - commit 6febcd9)

**Comment by gianm** [comment] 2017-03-22 22:16
@niketh, I tried locally and confirmed this is still a bug with the latest tranquility. It's fixed by updating Tranquility's Curator. After doing that, tranquility works against both Druid 0.10.0 and 0.9.2. Probably other versions too!

I'll send a Tranquility PR in a bit.

**Comment by gianm** [comment] 2017-03-22 22:18
Tranquillity patch at: https://github.com/druid-io/tranquility/pull/213. @niketh are you able to try that out? You can do a build by running:

```
sbt ++2.11.8 'project distribution' universal:packageZipTarball
```

**Comment by gianm** [comment] 2017-03-23 00:20
Marking 0.10.0 release notes, this should at least end up there if nothing else. Something along the lines of needing to update tranquility first if you're using that.

**Comment by gianm** [comment] 2017-03-23 15:24
Oops, closed accidentally.

**Comment by gianm** [comment] 2017-03-23 16:51
I raised https://issues.apache.org/jira/browse/CURATOR-394 with Curator. The root cause of this looks like a Curator bug. In this situation, it should be doable to upgrade Tranquility (the client) first and then Druid (the service), since Tranquillity doesn't announce itself so the "rolling upgrades are impossible" scenario I wrote up in the Curator JIRA doesn't apply.

Some questions:

- Should we revert the upgrade to Curator 2.12.0 (#4060) and wait for this to be sorted out upstream?
- If we stick with Curator 2.12.0, this issue means that Curator service discovery clients need to be updated before services. I think for Tranquility we can deal with this, but is there anything else in Druid where it'd be difficult to do this?

**Comment by gianm** [comment] 2017-03-23 16:55
My feeling is it makes sense to revert the Curator 2.12.0 upgrade.

**Comment by gianm** [comment] 2017-03-23 18:41
Talking with Jordan on CURATOR-394, it sounds like they may revert their change that broke stuff here, and do another Curator release. So for 0.10.0 I think we should revert back to the older Curator, and then revisit upgrading Curator in 0.10.1. I'll do a patch for that in a bit.

**Closed** 2017-03-23 20:44 UTC
Labels: Release Notes

**Comment by niketh** [comment] 2017-03-24 10:19
👍
