### ISSUE TITLE
Druid SQL Error: Unknown exception: io.druid.query.groupby.RowBasedColumnSelectorFactory$3 cannot be cast to io.druid.segment.LongColumnSelector

### ISSUE THREAD

**Issue by scan-the-automator** [druid-io/druid#4670] opened 2017-08-09 17:49 UTC
I have two queries that seem similar in nature, but one runs successfully while the other gives me the following error:

`Unknown exception: io.druid.query.groupby.RowBasedColumnSelectorFactory$3 cannot be cast to io.druid.segment.LongColumnSelector`

As far as I can tell the time column in query 2 is causing the error, however the same data types exist in query 1 (which runs) with the one difference being the case statement.  To make this more confusing, when I construct a similar case statement for query 2 it will run successfully.  Any ideas what might be the issue?  Thanks!

Query 1 (runs successfully)

```
select 
    floor(__time to day) as __time,
    fail_reason,
    count(primary_id)
from (
    select 
        max(__time) as __time,
        primary_id,
        case 
            when event_name = 'event_name_1' then 'failure'
            when event_name = 'event_name_2' and details_failed_reason = 'failed_reason_1' then 'failed_reason'
            else null
        end as fail_reason
    from data_source
    where 1=1
        and (event_name = 'event_name_1' or details_failed_reason = 'failed_reason_1')
        and floor(__time to day) > current_timestamp - interval '30' day
    group by primary_id, event_name, details_failed_reason
)
group by floor(__time to day), fail_reason
```

Query 2 (Does not run)

```
select
    floor(__time to hour) as __time,
    details_result,
    count(primary_id)
from (
    select 
        max(__time) as __time,
        primary_id,
        details_result
    from data_soure
    where 1=1
        and event_name = 'event_name_3'
        and floor(__time to day) > current_timestamp - interval '30' day
    group by primary_id,details_result
)
group by floor(__time to hour),details_result
```

**Comment by gianm** [comment] 2017-08-10 01:08
Definitely looks like a bug of some sort.

Does the inner query on query 2 run successfully if you run it by itself? This one:

```sql
select 
        max(__time) as __time,
        primary_id,
        details_result
    from data_soure
    where 1=1
        and event_name = 'event_name_3'
        and floor(__time to day) > current_timestamp - interval '30' day
    group by primary_id,details_result
```

And what version of Druid are running (or if you built it yourself, what commit)?

Finally: Could you contribute a test case for `io.druid.sql.calcite.CalciteQueryTest` that reproduces this error? That'd help a ton in tracking it down.

**Comment by scan-the-automator** [comment] 2017-08-10 18:19
Yeah, the inner query for query 2 runs successfully on its own.  If I remove __time from the outer query and just group by details_result it will also run successfully.

The version is 0.10.   Sorry, I don't know how to run java test cases :-(

**Comment by jihoonson** [comment] 2017-09-23 02:39
I'm looking into this. Interestingly, I can see a different exception with a similar query for the tpch lineitem table. Here is the query I tested and the exception.

```sql
select
    floor(__time to hour) as __time,
    l_linestatus,
    count(l_partkey)
from (
    select 
        max(__time) as __time,
        l_partkey,
        l_linestatus
    from lineitem_1g_split_year
    where 1=1
        and l_returnflag = 'R'
    group by l_partkey, l_linestatus
)
group by floor(__time to hour), l_linestatus
```

```
java.lang.RuntimeException: Error while applying rule DruidFilterRule, args [rel#337:LogicalFilter.NONE.[[]](input=rel#306:Subset#0.NONE.[],condition==($12, 'R')), rel#371:DruidQueryRel.NONE.[](query={"queryType":"scan","dataSource":{"type":"table","name":"lineitem_1g_split_year"},"intervals":{"type":"intervals","intervals":["-146136543-09-08T08:23:32.096Z/146140482-04-24T15:36:27.903Z"]},"virtualColumns":[],"resultFormat":"compactedList","batchSize":20480,"limit":9223372036854775807,"filter":null,"columns":["__time","count","l_comment","l_commitdate","l_discount","l_extendedprice","l_linenumber","l_linestatus","l_orderkey","l_partkey","l_quantity","l_receiptdate","l_returnflag","l_shipdate","l_shipinstruct","l_shipmode","l_suppkey","l_tax"],"legacy":false,"context":{},"descending":false})]
	at org.apache.calcite.plan.volcano.VolcanoRuleCall.onMatch(VolcanoRuleCall.java:235) ~[calcite-core-1.12.0.jar:1.12.0]
	at org.apache.calcite.plan.volcano.VolcanoPlanner.findBestExp(VolcanoPlanner.java:650) ~[calcite-core-1.12.0.jar:1.12.0]
	at org.apache.calcite.tools.Programs$RuleSetProgram.run(Programs.java:368) ~[calcite-core-1.12.0.jar:1.12.0]
	at org.apache.calcite.prepare.PlannerImpl.transform(PlannerImpl.java:313) ~[calcite-core-1.12.0.jar:1.12.0]
	at io.druid.sql.calcite.planner.DruidPlanner.planWithDruidConvention(DruidPlanner.java:148) ~[druid-sql-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at io.druid.sql.calcite.planner.DruidPlanner.plan(DruidPlanner.java:116) ~[druid-sql-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at io.druid.sql.http.SqlResource.doPost(SqlResource.java:88) [druid-sql-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_144]
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60) [jersey-server-1.19.3.jar:1.19.3]
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205) [jersey-server-1.19.3.jar:1.19.3]
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75) [jersey-server-1.19.3.jar:1.19.3]
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302) [jersey-server-1.19.3.jar:1.19.3]
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108) [jersey-server-1.19.3.jar:1.19.3]
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) [jersey-server-1.19.3.jar:1.19.3]
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84) [jersey-server-1.19.3.jar:1.19.3]
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542) [jersey-server-1.19.3.jar:1.19.3]
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473) [jersey-server-1.19.3.jar:1.19.3]
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419) [jersey-server-1.19.3.jar:1.19.3]
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409) [jersey-server-1.19.3.jar:1.19.3]
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409) [jersey-servlet-1.19.3.jar:1.19.3]
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558) [jersey-servlet-1.19.3.jar:1.19.3]
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733) [jersey-servlet-1.19.3.jar:1.19.3]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) [javax.servlet-api-3.1.0.jar:3.1.0]
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:286) [guice-servlet-4.1.0.jar:?]
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:276) [guice-servlet-4.1.0.jar:?]
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:181) [guice-servlet-4.1.0.jar:?]
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91) [guice-servlet-4.1.0.jar:?]
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85) [guice-servlet-4.1.0.jar:?]
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120) [guice-servlet-4.1.0.jar:?]
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135) [guice-servlet-4.1.0.jar:?]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759) [jetty-servlet-9.3.19.v20170502.jar:9.3.19.v20170502]
	at io.druid.server.security.PreResponseAuthorizationCheckFilter.doFilter(PreResponseAuthorizationCheckFilter.java:84) [druid-server-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759) [jetty-servlet-9.3.19.v20170502.jar:9.3.19.v20170502]
	at io.druid.server.security.AllowAllAuthenticator$1.doFilter(AllowAllAuthenticator.java:83) [druid-server-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at io.druid.server.security.AuthenticationWrappingFilter.doFilter(AuthenticationWrappingFilter.java:60) [druid-server-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759) [jetty-servlet-9.3.19.v20170502.jar:9.3.19.v20170502]
	at io.druid.server.security.SecuritySanityCheckFilter.doFilter(SecuritySanityCheckFilter.java:86) [druid-server-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759) [jetty-servlet-9.3.19.v20170502.jar:9.3.19.v20170502]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582) [jetty-servlet-9.3.19.v20170502.jar:9.3.19.v20170502]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:224) [jetty-server-9.3.19.v20170502.jar:9.3.19.v20170502]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180) [jetty-server-9.3.19.v20170502.jar:9.3.19.v20170502]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512) [jetty-servlet-9.3.19.v20170502.jar:9.3.19.v20170502]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185) [jetty-server-9.3.19.v20170502.jar:9.3.19.v20170502]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112) [jetty-server-9.3.19.v20170502.jar:9.3.19.v20170502]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.3.19.v20170502.jar:9.3.19.v20170502]
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:493) [jetty-server-9.3.19.v20170502.jar:9.3.19.v20170502]
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52) [jetty-server-9.3.19.v20170502.jar:9.3.19.v20170502]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134) [jetty-server-9.3.19.v20170502.jar:9.3.19.v20170502]
	at org.eclipse.jetty.server.Server.handle(Server.java:534) [jetty-server-9.3.19.v20170502.jar:9.3.19.v20170502]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320) [jetty-server-9.3.19.v20170502.jar:9.3.19.v20170502]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251) [jetty-server-9.3.19.v20170502.jar:9.3.19.v20170502]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283) [jetty-io-9.3.19.v20170502.jar:9.3.19.v20170502]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:108) [jetty-io-9.3.19.v20170502.jar:9.3.19.v20170502]
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93) [jetty-io-9.3.19.v20170502.jar:9.3.19.v20170502]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303) [jetty-util-9.3.19.v20170502.jar:9.3.19.v20170502]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148) [jetty-util-9.3.19.v20170502.jar:9.3.19.v20170502]
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136) [jetty-util-9.3.19.v20170502.jar:9.3.19.v20170502]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671) [jetty-util-9.3.19.v20170502.jar:9.3.19.v20170502]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589) [jetty-util-9.3.19.v20170502.jar:9.3.19.v20170502]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_144]
Caused by: java.lang.RuntimeException: Error occurred while applying rule DruidFilterRule
	at org.apache.calcite.plan.volcano.VolcanoRuleCall.transformTo(VolcanoRuleCall.java:148) ~[calcite-core-1.12.0.jar:1.12.0]
	at org.apache.calcite.plan.RelOptRuleCall.transformTo(RelOptRuleCall.java:225) ~[calcite-core-1.12.0.jar:1.12.0]
	at io.druid.sql.calcite.rule.DruidFilterRule.onMatch(DruidFilterRule.java:58) ~[druid-sql-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at org.apache.calcite.plan.volcano.VolcanoRuleCall.onMatch(VolcanoRuleCall.java:211) ~[calcite-core-1.12.0.jar:1.12.0]
	... 62 more
Caused by: java.lang.UnsupportedOperationException: replaceInput called on rel#374:DruidOuterQueryRel.NONE.[](innerQuery=rel#358:Subset#11.NONE.[],query={"queryType":"groupBy","dataSource":{"type":"table","name":"__subquery__"},"intervals":{"type":"intervals","intervals":["-146136543-09-08T08:23:32.096Z/146140482-04-24T15:36:27.903Z"]},"virtualColumns":[],"filter":null,"granularity":{"type":"all"},"dimensions":[{"type":"extraction","dimension":"a0","outputName":"d0","outputType":"LONG","extractionFn":{"type":"timeFormat","format":null,"timeZone":null,"locale":null,"granularity":"HOUR","asMillis":true}},{"type":"default","dimension":"d0","outputName":"d1","outputType":"STRING"}],"aggregations":[{"type":"filtered","aggregator":{"type":"count","name":"a0"},"filter":{"type":"not","field":{"type":"selector","dimension":"d1","value":"","extractionFn":null}},"name":"a0"}],"postAggregations":[],"having":null,"limitSpec":{"type":"NoopLimitSpec"},"context":{},"descending":false})
	at org.apache.calcite.rel.AbstractRelNode.replaceInput(AbstractRelNode.java:372) ~[calcite-core-1.12.0.jar:1.12.0]
	at org.apache.calcite.plan.volcano.VolcanoPlanner.fixUpInputs(VolcanoPlanner.java:1379) ~[calcite-core-1.12.0.jar:1.12.0]
	at org.apache.calcite.plan.volcano.VolcanoPlanner.rename(VolcanoPlanner.java:1249) ~[calcite-core-1.12.0.jar:1.12.0]
	at org.apache.calcite.plan.volcano.RelSet.mergeWith(RelSet.java:345) ~[calcite-core-1.12.0.jar:1.12.0]
	at org.apache.calcite.plan.volcano.VolcanoPlanner.merge(VolcanoPlanner.java:1413) ~[calcite-core-1.12.0.jar:1.12.0]
	at org.apache.calcite.plan.volcano.VolcanoPlanner.rename(VolcanoPlanner.java:1291) ~[calcite-core-1.12.0.jar:1.12.0]
	at org.apache.calcite.plan.volcano.RelSet.mergeWith(RelSet.java:345) ~[calcite-core-1.12.0.jar:1.12.0]
	at org.apache.calcite.plan.volcano.VolcanoPlanner.merge(VolcanoPlanner.java:1413) ~[calcite-core-1.12.0.jar:1.12.0]
	at org.apache.calcite.plan.volcano.VolcanoPlanner.registerSubset(VolcanoPlanner.java:1669) ~[calcite-core-1.12.0.jar:1.12.0]
	at org.apache.calcite.plan.volcano.VolcanoPlanner.registerImpl(VolcanoPlanner.java:1530) ~[calcite-core-1.12.0.jar:1.12.0]
	at org.apache.calcite.plan.volcano.VolcanoPlanner.register(VolcanoPlanner.java:863) ~[calcite-core-1.12.0.jar:1.12.0]
	at org.apache.calcite.plan.volcano.VolcanoPlanner.ensureRegistered(VolcanoPlanner.java:883) ~[calcite-core-1.12.0.jar:1.12.0]
	at org.apache.calcite.plan.volcano.VolcanoPlanner.ensureRegistered(VolcanoPlanner.java:1769) ~[calcite-core-1.12.0.jar:1.12.0]
	at org.apache.calcite.plan.volcano.VolcanoRuleCall.transformTo(VolcanoRuleCall.java:135) ~[calcite-core-1.12.0.jar:1.12.0]
	at org.apache.calcite.plan.RelOptRuleCall.transformTo(RelOptRuleCall.java:225) ~[calcite-core-1.12.0.jar:1.12.0]
	at io.druid.sql.calcite.rule.DruidFilterRule.onMatch(DruidFilterRule.java:58) ~[druid-sql-0.11.0-SNAPSHOT.jar:0.11.0-SNAPSHOT]
	at org.apache.calcite.plan.volcano.VolcanoRuleCall.onMatch(VolcanoRuleCall.java:211) ~[calcite-core-1.12.0.jar:1.12.0]
	... 62 more
```

**Comment by jihoonson** [comment] 2017-09-26 08:45
I raised https://github.com/druid-io/druid/issues/4847 because it looks that this error is different from the original one.

**Comment by drcrallen** [comment] 2017-09-26 17:11
There have been a lot of updates since 0.10.0 in this code area. This will be closed as "Unable to reproduce" until a reproducible test case against a recent release can be created.

**Comment by gianm** [comment] 2017-09-26 17:11
@scan-the-automator when the 0.11.0-rc1 is out, could you please try to reproduce this error with that build, and if it still happens, reopen this issue?

**Closed by drcrallen** 2017-09-26 17:11 UTC
Labels: Area - SQL, Bug
