### ISSUE TITLE
BUG: select query do not support empty dimensions/metrics list in 0.8.3-rc2

### ISSUE THREAD

**Issue by hamlet-lee** [druid-io/druid#2177] opened 2015-12-31 10:17 UTC
query like this not work now!
```
{
    "queryType": "select",
    "dataSource": "ZhuanYeFanyi",
    "granularity": "all",
    "dimensions": [],
    "metrics": [],
    "intervals": [
        "2015-12-26T00:00:00+08:00/2015-12-31T00:00:00+08:00"
    ],
    "pagingSpec": {
        "pagingIdentifiers": {},
        "threshold": 1
    }
}
```
error message:

```
com.fasterxml.jackson.databind.JsonMappingException: Unexpected end-of-input: expected close marker for OBJECT (from [Source: java.io.SequenceInputStream@663e37b8; line: -1, column: -1]) at [Source: java.io.SequenceInputStream@663e37b8; line: -1, column: 2104] (through reference chain: java.util.ArrayList[0])
```

if I use this query, no error shown.
```
{
    "queryType": "select",
    "dataSource": "ZhuanYeFanyi",
    "granularity": "all",
    "dimensions": ["a"],
    "metrics": ["b"],
    "intervals": [
        "2015-12-26T00:00:00+08:00/2015-12-31T00:00:00+08:00"
    ],
    "pagingSpec": {
        "pagingIdentifiers": {},
        "threshold": 1
    }
}
```

**Comment by fjy** [comment] 2015-12-31 16:26
@hamlet-lee Thanks for reporting this. Was this working in 0.8.2?

Any chance you can contribute a unit test for help reproduce the problem?

**Comment by hamlet-lee** [comment] 2016-01-04 05:20
@fjy I have tried some cases, and found that this bug only happened when there is a "thetaSketch" aggregator.

I am glad to provide testcases, but I am not that familiar with github flow and druid code currently.  Would you give some hint on:
1) any similar testcases?
2) which branch should I add this test case? 0.8.3?

**Comment by fjy** [comment] 2016-01-04 05:33
@hamlet-lee please submit a PR to master. 0.8.3 is a stable release.

You can submit the test here and add a case for the select query: https://github.com/druid-io/druid/blob/master/extensions/datasketches/src/test/java/io/druid/query/aggregation/datasketches/theta/SketchAggregationTest.java

**Comment by himanshug** [comment] 2016-01-04 15:51
@hamlet-lee thanks for checking, i will try and repro it to see whatz wrong.

**Comment by himanshug** [comment] 2016-01-05 05:38
@hamlet-lee is it possible for you to test the patch https://github.com/himanshug/druid/pull/2 ? I need to find more time to test it myself, will be great if you could test it and confirm if that solves the problem

**Comment by hamlet-lee** [comment] 2016-01-05 14:17
@himanshug Let me try

**Comment by hamlet-lee** [comment] 2016-01-05 15:33
@himanshug It is more difficult than expect to run your version.  When I start overlord service, it just fail, looks like it does not load extensions I configured (I have run 'mvn install' on your code, and succeed).
 
So, you'd better try by yourself.  If possible, you can try: 
1) create a segment with thetaSketch
2) send a "select"  query with empty dimensions and metrics list

**Comment by hamlet-lee** [comment] 2016-01-06 00:37
@himanshug I have tested your version.  the bug is fixed.

**Comment by drcrallen** [comment] 2016-01-06 00:39
@himanshug It is not clear from this thread that the fix is in Master, can you please clarify the status of the fix?

**Comment by himanshug** [comment] 2016-01-06 03:12
@drcrallen yes its not in druid just yet, i had created a PR in my own fork so that @hamlet-lee  could see/test the fix.
@hamlet-lee thanks for confirmation.

will send a PR to druid repo.

**Comment by himanshug** [comment] 2016-01-06 04:02
this is duplicate of #2178

**Closed** 2016-01-06 04:03 UTC
