### ISSUE TITLE
[feature request] Expose metric aggregation information in segment metadata

### ISSUE THREAD

**Issue by mistercrunch** [druid-io/druid#1587] opened 2015-08-01 15:08 UTC
Is this captured in the metadata database already and just a matter of surfacing it in the API call, or is it not captured outside of the segments themselves?

**Comment by fjy** [comment] 2015-08-06 23:10
The rollup isn't captured in the segment metadata right now. However, we are adding support for this. This is actually a duplicate of https://github.com/druid-io/druid/issues/1514

**Closed** 2015-08-06 23:10 UTC
