### ISSUE TITLE
version field of HadoopTuningConfig is always set to default value

### ISSUE THREAD

**Issue by sirpkt** [druid-io/druid#3155] opened 2016-06-16 02:57 UTC
http://druid.io/docs/latest/ingestion/batch-ingestion.html says that user can specify `version` of segments.
But, `HadoopIndexTask` always replaces `version` with DateTime of indexing start time (which is default when no version is given).

I'm not sure the behavior of `HadoopIndexTask` is intended or not 
but I think it needs consistency between docs and implementation.

**Comment by fjy** [comment] 2016-06-16 05:24
Hi Keuntae, this is likely a bug as if you provide a version explicitly in
the config, Druid should respect that version.

**Comment by gianm** [comment] 2016-06-16 16:54
Actually this is by design when using the indexing service, the user-provided `version` is always ignored in favor of the internally generated version (to assure data consistency). So we should update the docs. While we're at it we might as well also document the other properties that are ignored for the indexing service:

- metadataUpdateSpec
- workingPath
- segmentOutputPath
- version

thanks for pointing this out @sirpkt.

**Comment by gianm** [comment] 2017-02-21 17:47
fixed by #3557

**Closed by gianm** 2017-02-21 17:47 UTC
Labels: Documentation
