### ISSUE TITLE
Transient test failure - KafkaIndexTaskTest. testRunOnNothing - NullPointerException

### ISSUE THREAD

**Issue by drcrallen** [druid-io/druid#3039] opened 2016-05-31 14:51 UTC
As per https://travis-ci.org/druid-io/druid/jobs/133474341

```
testRunOnNothing[buildV9Directly = true](io.druid.indexing.kafka.KafkaIndexTaskTest)  Time elapsed: 50.725 sec  <<< ERROR!
java.lang.NullPointerException: null
    at io.druid.indexing.kafka.KafkaIndexTaskTest.tearDown(KafkaIndexTaskTest.java:274)
```

**Comment by gianm** [comment] 2017-02-13 22:38
This looks like a duplicate of #3038; the root cause of this NPE was that tearDown was trying to tear down things that hadn't ever been made, because setUp failed:

```
org.I0Itec.zkclient.exception.ZkTimeoutException: Unable to connect to zookeeper server within timeout: 30000
	at org.I0Itec.zkclient.ZkClient.connect(ZkClient.java:1223)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:155)
	at org.I0Itec.zkclient.ZkClient.<init>(ZkClient.java:129)
	at kafka.utils.ZkUtils$.createZkClientAndConnection(ZkUtils.scala:89)
	at kafka.utils.ZkUtils$.apply(ZkUtils.scala:71)
	at kafka.server.KafkaServer.initZk(KafkaServer.scala:278)
	at kafka.server.KafkaServer.startup(KafkaServer.scala:168)
	at io.druid.indexing.kafka.test.TestBroker.start(TestBroker.java:73)
	at io.druid.indexing.kafka.KafkaIndexTaskTest.setUp(KafkaIndexTaskTest.java:248)
```

**Closed by gianm** 2017-02-13 22:38 UTC
Labels: Testing
