### ISSUE TITLE
ingestSegment Firehose to support partitioned data segments.

### ISSUE THREAD

**Issue by luxuec** [druid-io/druid#1052] opened 2015-01-19 04:46 UTC

**Comment by drcrallen** [comment] 2015-01-19 16:33
Hi @luxuec : can you please provide more information on this, like an example use case?

**Comment by drcrallen** [comment] 2015-01-19 16:39
Is this a duplicate of #1053 ?

**Comment by fjy** [comment] 2015-01-19 20:36
Duplicated by #1053

**Comment by nishantmonu51** [comment] 2015-06-03 09:24
fixed by #1190

**Closed by nishantmonu51** 2015-06-03 09:24 UTC
