### ISSUE TITLE
Data loss in druid 

### ISSUE THREAD

**Issue by pdeva** [druid-io/druid#1160] opened 2015-03-01 07:05 UTC
As you can see in this screenshot, I have lost data between 4:00 and 15:00
http://screencast.com/t/c5zlZ1X0mHD4

I am using druid 0.6.160

I have 2 realtime nodes (1 replicating the other). None of my nodes went down.

My historical nodes however, did get full and querying became real slow until i added another node around 5:00 pm though. Not sure if that affects this somehow.

Also I see very high disk space usage for my realtime nodes.

**Comment by drcrallen** [comment] 2015-03-02 03:01
![Timeline plot with missing data](http://content.screencast.com/users/PrashantDeva/folders/Jing/media/f218b65a-7e2a-449d-9ffa-6284a2aa407e/2015-02-28_2242.png)

**Comment by nishantmonu51** [comment] 2015-03-02 10:25
can you also share logs for the realtime nodes for the period when data is lost ? 
the high disk space on realtime nodes can be due to segments not being handed over to historicals as they were full.

**Comment by pdeva** [comment] 2015-03-02 20:49
Here are the logs from now to 4 days back:

Realtime node 1
https://dl.dropboxusercontent.com/u/152963/druid/druid-realtime1.txt.gz

Realtime node 2
https://dl.dropboxusercontent.com/u/152963/druid/druid-realtime2.txt.gz

all times in the logs are in UTC.

The time shown in the screenshot is in PST.

**Comment by fjy** [comment] 2015-03-03 02:01
@pdeva Can you show us the output of the loadstatus endpoint on the coordinator? Are you sure you have enough capacity right now to hand off segments and load new segments?

**Comment by fjy** [comment] 2015-03-03 02:12
@pdeva Looking at your logs, you've appear to have configured some metrics as dimensions. Can you share your ingestion spec as well? It looks like some of your segments were corrupt and unable to be loaded.

**Comment by pdeva** [comment] 2015-03-03 03:50
@fjy doing /loadstatus.html gives 404.
but i guess this is the info you are looking for:
http://screencast.com/t/RsKnLUJsb

**Comment by pdeva** [comment] 2015-03-03 03:51
here is the spec

```
 {
    "schema": {
      "dataSource": "dripstat",
      "aggregators": [
        {
          "type": "count",
          "name": "count"
        },
        {
          "type": "doubleSum",
          "name": "min",
          "fieldName": "min"
        },
        {
          "type": "doubleSum",
          "name": "max",
          "fieldName": "max"
        },
        {
          "type": "longSum",
          "name": "callCount",
          "fieldName": "callCount"
        },
        {
          "type": "longSum",
          "name": "errcount",
          "fieldName": "errcount"
        },
        {
          "type": "doubleSum",
          "name": "totalTime",
          "fieldName": "totalTime"
        },
        {
          "type": "doubleSum",
          "name": "value",
          "fieldName": "value"
        },
        {
          "type": "doubleSum",
          "name": "traceduration",
          "fieldName": "traceduration"
        }
      ],
      "indexGranularity": "none",
      "shardSpec": {
        "type": "linear",
        "partitionNum": 0
      }
    },
    "config": {
      "maxRowsInMemory": 50000,
      "intermediatePersistPeriod": "PT10m"
    }

```

**Comment by fjy** [comment] 2015-03-03 04:04
@pdeva what is the link you are trying to use to get loadstatus?

**Comment by fjy** [comment] 2015-03-03 04:04
@pdeva Please go to coordinator_ip:port/druid/coordinator/v1/loadstatus

**Comment by pdeva** [comment] 2015-03-03 04:05
ok i didnt know about that url.
here is the output:

```
{"dripstat":100.0}
```

**Comment by fjy** [comment] 2015-03-03 04:09
@pdeva your data appears to be fully loaded based on what is in the metadata store. 

can you please show me the json for the firehose?

**Comment by pdeva** [comment] 2015-03-03 04:11
here is the rest of the spec file with the firehose json:

```
"firehose": {
      "type": "kafka-0.8",
      "consumerProps": {
        "zookeeper.connect": "xx.dripstat.com:2181,xx2.dripstat.com:2181,xx3.dripstat.com:2181",
        "zookeeper.connection.timeout.ms": "15000",
        "zookeeper.session.timeout.ms": "15000",
        "zookeeper.synctime.ms": "5000",
        "group.id": "druid-dripstat",
        "fetch.size": "1048586",
        "auto.offset.reset": "largest",
        "auto.commit.enable": "false"
      },
      "feed": "dripstat",
      "parser": {
        "timestampSpec": {
          "column": "timestamp"
        },
        "data": {
          "format": "json"
        }
      }
    },
    "plumber": {
      "type": "realtime",
      "windowPeriod": "PT10m",
      "segmentGranularity": "hour",
      "basePersistDirectory": "/drdata/realtime/basePersist"
    }
  }
```

**Comment by fjy** [comment] 2015-03-03 04:15
@pdeva You are hitting some casing problems. I suspect your queries for totaltime and callcount will not return anything. You can either specify all the dimensions of your data set, or lower case the following on your schema.

        {
          "type": "longSum",
          "name": "callCount",
          "fieldName": "callCount"
        },
        {
          "type": "doubleSum",
          "name": "totalTime",
          "fieldName": "totalTime"
        },

**Comment by pdeva** [comment] 2015-03-03 04:17
hmm we have had the same casing since we started using druid > 6 months ago and they do work fine. in fact they are working fine right now.
its just that those 12 hrs of data are completely missing. otherwise the rest works.

**Comment by fjy** [comment] 2015-03-03 04:21
For the 12 hours missing, are there any entries in the metadata store for them?

**Comment by pdeva** [comment] 2015-03-03 04:22
umm not sure what you mean by 'metadata store' here.
you mean i should query the mysql?

**Comment by fjy** [comment] 2015-03-03 04:23
yes, look in mysql and see if any entries exist for the missing segments

**Comment by pdeva** [comment] 2015-03-03 04:31
so, this issue happen on Feb 28 in PST at around 5 am.
That is Feb 28 1:00 PM in UTC.

It seems those segments are indeed missing:
http://screencast.com/t/1t6cg7lJKrP

what can cause this?

**Comment by fjy** [comment] 2015-03-03 04:52
The logs you provided start at:
2015-03-02 20:09:50,299

Please provide the logs for the time period where segments did not write to the metadata storage

**Comment by pdeva** [comment] 2015-03-04 04:24
Here are the logs for the entire day of Feb 28 

Realtime-1
https://dl.dropboxusercontent.com/u/152963/druid/realtime1-feb28.txt

Realtime-2
https://dl.dropboxusercontent.com/u/152963/druid/realtime2-feb28.zip

**Comment by fjy** [comment] 2015-03-06 19:05
@pdeva The first log is just a few exception messages with no timestamps.

The second log starts at 2015-02-28 23:59:10,308

**Comment by pdeva** [comment] 2015-03-06 19:15
@fjy the logs for realtime 2 are in reverse order. It starts at 23:17 if you scroll down.
For some reason splunk doesnt seem to have logs before this.

For realtime1, yes it seems splunk didnt output the timestamps here.
Here is a screenshot showing timestamps
http://screencast.com/t/746w95gr5CxZ

**Comment by fjy** [comment] 2015-03-06 20:52
@pdeva, we can't really debug anything without seeing the logs for handoff for the hours that failed.

The logs you've provided indicate a successful handoff and do not correspond to the hours of data where data is missing.

**Comment by fjy** [comment] 2015-03-06 20:58
@pdeva I suspect what happened was that your historicals was completely full so realtime nodes could not hand off. After some time, the real-time nodes began throttling themselves to prevent crashing and stopped ingesting new data. At a later point in time, you added new historicals and the ingestion process recovered. However, the events the realtime read were outside its window period, and was dropped on the floor, which is the expected behavior for events outside the window period.

What we do in production is we monitor to add new nodes as our cluster grows, and we have an accompanying batch ingestion process to load older data just in case something in our ingestion pipeline breaks.

**Comment by fjy** [comment] 2015-03-06 20:58
I am going to close the issue for now. Please reopen if you find my hypothesis in correct.

**Closed by fjy** 2015-03-06 20:58 UTC
