### ISSUE TITLE
Multi-value fields do not mix well with lookups

### ISSUE THREAD

**Issue by gvsmirnov** [druid-io/druid#3414] opened 2016-08-31 15:05 UTC
For the simplest example, consider datasource that has a record that contains a multi-value field:

``` (js)
{ "key": ["key1", "key2"], /* ... */ }
```

A query is made with the following dimension spec:

```
"dimensions" : [
  {
    "type" : "default",
    "dimension" : "key",
    "outputName" : "key"
  }, {
    "type" : "extraction",
    "dimension" : "key",
    "outputName" : "value",
    "extractionFn" : {
      "type": "lookup",
      "lookup": {
        "type": "map",
        "map" : { "key1": "value1", "key2": "value2" }
      }
    }
  },
  /* ... */
]
```

Intuitively, I would expect to have the following two rows returned:

```
{ "key": "key1", "value": "value1", /*...*/}
{ "key": "key2", "value": "value2", /*...*/}
```

However, instead I get this:

```
{ "key": "key1", "value": "value1", /*...*/}
{ "key": "key1", "value": "value2", /*...*/}
{ "key": "key2", "value": "value1", /*...*/}
{ "key": "key2", "value": "value2", /*...*/}
```

---

I do understand why it may currently work this way, but I do believe a much better user experience can be achieved in such cases. In fact, as far as I understand, there currently is no good solution for this use case and also for filtering by lookup result on a multi-value field. A possible workaround is to change the lookup to be like `{"key1": "key1:value1"}`, but that does not work well for non-injective lookups and is generally very ugly.

I was unable to find any discussion of this topic, so it would be great if someone could elaborate on this. I am ok with taking time to implement a nice solution, but would like to have an agreement on the expected behavior. A possible solution could be to optionally (if a parameter is set to `true`) return the original pre-lookup value along with the value that was looked up, although I'm pretty sure there can be better ways.

**Comment by drcrallen** [comment] 2016-08-31 15:07
Can you elaborate on what query you are doing that gets these results? (topN, groupBy?)

**Comment by drcrallen** [comment] 2016-08-31 15:08
nevermind :) groupby given the multiple dimension spec

**Comment by drcrallen** [comment] 2016-08-31 15:10
I'm pretty sure Dimension tuples should roll up together in a groupBy.

**Comment by gvsmirnov** [comment] 2016-08-31 15:14
Uh, I'm not sure I understand what you mean by Dimension tuples being rolled up. Could you elaborate, please?

**Comment by gianm** [comment] 2016-08-31 15:28
@gvsmirnov, your query is grouping on two multi-value dimensions ('key' and another one 'value' created from key). Since Druid explodes multi-value dimensions when grouping, that means you get the cross product out.

I think what you're looking for is for Druid to treat 'value' as something derived from 'key' and not as a separate independent dimension. You might be able to do that with a custom extraction function that does basically `f(x) = x + ":" + lookup(x)`, and then only including the extracted dimension in your grouping (not the original one). Or by patching the existing lookup extraction function to have an option to prepend the key.

**Comment by drcrallen** [comment] 2016-08-31 15:28
I would expect each combination of dimension values to appear only once, as per your expected behavior.

**Comment by drcrallen** [comment] 2016-08-31 15:29
@gianm You made a lot of improvements in the groupBy engine for an upcoming release, does this strike you as an unintended side-effect somewhere? and do you know if the new grouper does the same thing?

**Comment by gvsmirnov** [comment] 2016-08-31 15:33
@gianm that was my idea for the workaround, too. Brushing aside the kludginess, this would not work for non-injective lookups where one wants to group by the value that was looked up.

**Comment by drcrallen** [comment] 2016-08-31 15:35
I miss-read the report.
Does `{ "key": "key2", "value": "value1", /*...*/}` have anything in it?

it looks like it is rolling up dimension tuples, but you just have more tuples than you expect

**Comment by gianm** [comment] 2016-08-31 15:39
@drcrallen this seems to me like intended (but possibly unintuitive) behavior. But both engines do the same thing where any multi-value dimension gets independently exploded, yielding a cross product. I just wrote a PR with a new test for that: #3415

@gvsmirnov if you're wanting to group by the looked up value on a non-injective lookup, you probably don't want to include the key at all, right? Since it would potentially vary and interfere with the grouping. So you could use the version/option of the extraction function that doesn't prepend the key in that case.

**Comment by drcrallen** [comment] 2016-08-31 15:41
Ok, I get it now, thanks @gianm for that good test.

I was wrong previously. Due to the fact that the multi-value dimension is both value1 **and** value2, the behavior presented by druid and shown by @gianm in tests is the correct behavior as groupBy stands today.

This definitely deserves to be called out in docs.

**Comment by drcrallen** [comment] 2016-08-31 15:45
Given that the multi-value dimension takes on both values, @gvsmirnov, can you elaborate on what kind of behavior would be helpful?

**Comment by drcrallen** [comment] 2016-08-31 15:45
It does no good to return a bunch of data that isn't actually useful or intended.

**Comment by gvsmirnov** [comment] 2016-08-31 15:49
@drcrallen @gianm yep, I do understand that both `key` and `value` end up being multi-value dimensions currently. However, IMO it would make sense to, if a lookup is using a multi-value dimension (`key`) as a source, to apply it after the `key` is unrolled into `key1` and `key2`, to each individually.

Do you think that the current cross-product behavior is a more viable use case than returning only rows where the lookup result actually corresponds to the lookup key?

@gianm fair point about not wanting to keep the key at all if grouping by a non-injective lookup. Still, the workaround is quite a sad one.

**Comment by gvsmirnov** [comment] 2016-08-31 15:53
To clarify: I believe the helpful behavior would be to only return rows where the looked-up value corresponds to the look-up key.

**Comment by gianm** [comment] 2016-08-31 15:58
fwiw, I think the current groupBy behavior when you have two multi-value dims is "correct" and internally consistent with how multi-value dims are generally dealt with, but is probably not actually that useful.

@gvsmirnov I think the question there is, how does Druid know that you want to treat key/value as a single unit, rather than as two completely independent dimensions? The way you provide them in the query (two separate dimensions) tells Druid they should be treated independently. IMO if they should be treated as a unit, they should be provided as one dimension, which points towards the extraction function "workaround" as actually being a good approach, since that is one dimension rather than two.

I wonder what's sad about it? Would it be less sad if we could return `"kv" : {"k": "k1", "v": "v1"}` rather than `"kv": "k1:v1"`?

**Comment by drcrallen** [comment] 2016-08-31 15:59
@gvsmirnov can you see if https://github.com/druid-io/druid/issues/3367 captures your needs adequately? it would be worth commenting there that you have a use-case for multi-value dimensions. If that does capture the needs correctly I propose closing this down as working as intended (confusing though it is) and having only one issue for "id and value" being returned for lookups.

**Comment by gvsmirnov** [comment] 2016-08-31 16:15
@gianm  I would expect it to know it by seeing that in the dimension spec:

```
"dimensions" : [
  {
    "type" : "default",
    "dimension" : "key", // <-
    "outputName" : "key"
  }, {
    "type" : "extraction",
    "dimension" : "key", // <-
    "outputName" : "value",
    "extractionFn" : {...}
  }
]
```

There are two entries that have the same `"dimension"` field. That means that they share the same source and should be treated as a single unit.

As for the sadness, consider a case where you are looking up an object by id, and the object has multiple fields, and you would like to be able to filter by those fields, too. Now you could have the whole object as a string and then do some perversions for filtering and then splitting etc. Another part of the sadness is that I don't see a way to prepend the original Id besides putting it in the lookup source data (e.g. a kafka topic would contain mappings like `key1->key1:value1`, which is sad in itself. Or am I missing a way to do the prepending without it?

@drcrallen partially it would, yes. But consider the case where the object looked up has multiple properties that the user wants to filter by. A nice approach would be to have them all as separately looked-up dimensions.

Since from the query it's obvious that multiple output dimensions are based on the same dimension in the source data, then Druid can be nice enough to avoid cross-producting the dimension essentially with itself multiple times.

**Comment by gvsmirnov** [comment] 2016-08-31 16:18
Also a part of the sadness of the workaround: if you want the looked-up value to match exactly yo `xyz`, you cannot use a simple `selector` filter.

**Comment by gianm** [comment] 2016-08-31 16:19
@gvsmirnov putting the key in the source lookup is probably not the best way to go, for the all reasons you mentioned (extra data in kafka, interferes with filtering, can't be disabled, etc…). I was thinking more like an option in the extraction function for prepending the key, which you could enable or disable at query time.

**Comment by gianm** [comment] 2016-08-31 16:21
Specifically I was thinking of something like, `"includeKey": true, "keyDelimiter": "|"` as things you could ask the extraction function to do. That would probably solve #3367 as well. It wouldn't be as nice as returning a real JSON object but it would be easy to fit into the existing system.

**Comment by gianm** [comment] 2016-08-31 16:23
One important thing here is that the dimension you group by and the dimension you filter by do not have to be defined the same way. You could filter by value and then group by "key:value", and that would work fine.

**Comment by gvsmirnov** [comment] 2016-08-31 16:25
How about having something like this:

```js
{
  "dimension": "key",
  "type": "multiOutput",
  "output": [
     {"type": "default" ...},
     {"type": "extraction" ...}
  ]
}

```

**Comment by gianm** [comment] 2016-08-31 16:27
@gvsmirnov what would the query result look like in that case?

**Comment by gvsmirnov** [comment] 2016-08-31 16:39
That may vary. For example, given

```js
{
  "dimension": "key",
  "type": "multiOutput",
  "output": [
     {"type": "default", "outputName": "key"},
     {
      "type": "extraction",
      "outputName": "someLookupValue",
      "extractionFn" : {
        "type": "lookup",
        "lookup": {
          "type": "map",
          "map" : { "key1": "someValue1", "key2": "someValue2" }
        }
      }
     },
     {
      "type": "extraction",
      "outputName": "someOtherLookupValue",
      "extractionFn" : {
        "type": "lookup",
        "lookup": {
          "type": "map",
          "map" : { "key1": "someOtherValue1", "key2": "someOtherValue2" }
        }
      }
     }
  ]
}
```

And a record like `{"key": ["key1", "key2"] /*...*/}`

I'd be ok to get

```
{ "key": "key1", "someLookupValue": "someValue1", "someOtherLookupValue": "someOtherValue1", /*...*/}
{ "key": "key2", "someLookupValue": "someValue2", "someOtherLookupValue": "someOtherValue2", /*...*/}
```

But basically, this kind of spec would clearly express the intent that for each value of `"key"`, each output should computed once, and each output value should be in the record corresponding to the key.

**Comment by gvsmirnov** [comment] 2016-08-31 16:44
If you give me a few pointers on where to start, I'd be ok to implement it while avoiding clubbering everything around :)

**Comment by gianm** [comment] 2016-08-31 18:39
If you wanted to do the extractionFn options, they could be added to RegisteredLookupExtractionFn, LookupExtractionFn, and LookupDimensionSpec (the three internal ways lookups can get used). It might be nice to generalize them a bit, i.e. rather than having keyDelimiter, instead have a "format string" that could be something like "%k:%v" or "%v (%k)" or whatever. Perhaps also an option to escape keys/values to handle the case where it's not possible to select an un-ambiguous format string.

I think your multiOutput suggestion is not implementable right now, since dimension values currently need to be strings. We are working on lifting that restriction but there's a bunch of internal refactoring needed.

**Comment by gvsmirnov** [comment] 2016-09-04 11:26
@gianm aha, after looking through the codebase I see that making this `multiOutput` would require touching a lot of code. I currently (grudgingly :) ) implemented the workaround with just concatenating stuff, so my need is not so urgent any more.

IMO it would be much better to implement only the long-term solution, as the additional extractionFn option is quite a half-measure. Where could I track the progress of lifting the restriction on string-only values, by the way? I found an assortment of various issues related to that, but no umbrella discussion.

**Comment by gianm** [comment] 2016-10-14 00:57
@gvsmirnov there have been some discussions about opening up extractionFn return types to numerics as well as strings, but not yet to more complex types like list, map, etc.

**Comment by gianm** [comment] 2017-10-24 01:26
An update: Druid extractionFns still can only return strings, but expressions can return numerics. They can't return complex types, but may be generalized at some point (list is particularly likely).

Closing this, since it seems like the original issue has been solved or worked around.

**Closed by gianm** 2017-10-24 01:26 UTC
