### ISSUE TITLE
Kafka Index tasks sotps consuming any data 

### ISSUE THREAD

**Issue by pjain1** [druid-io/druid#3467] opened 2016-09-19 20:19 UTC
When a Kafka index task successfully publishes some segments then it persists the latest consumed offsets info in the metadata store. Now if the supervisor is stopped or stops because of some reason and restarted at a later point and the earliest msg offset in Kafka is greater than persisted offset in the metadata (probably because earlier messages were dropped by kafka brokers or something else) then Kafka Index task will get `OffsetOutOfRangeException` and keep on retrying the same offset indefinitely.  

One way to solve this issue is to reset the consumer offset if the persisted offset is less than the earliest offset at the Kafka broker. Although I think in this case the persisted offset information would need to be delete from metadata store otherwise the new tasks will fail to publish segment because of consecutive offset check. Any thoughts ?

**Comment by gianm** [comment] 2016-09-19 20:25
@pjain1 what you are describing sounds like the intended behavior- once messages up to offset X are read, the tasks should wait for offset X+1 to appear. If no new messages ever appear then they will wait indefinitely.

Maybe what you want is #3195?

**Comment by gianm** [comment] 2016-09-19 20:27
Actually #3195's problem statement is not exactly what I think your problem is, but the solution might be the same. The solution could be an API that resets a supervised Kafka ingestion back to the start of a topic.

**Comment by pjain1** [comment] 2016-09-19 20:32
#3195 is exactly what I am trying to define here, sorry if the explanation was not clear.

**Comment by dclim** [comment] 2016-09-19 21:11
@pjain1 awesome - I'll close this issue since it's a duplicate of #3195 and will look into adding the reset API soonish; but like you mentioned, in the meantime you can get around this by removing the row for that datasource from the druid_dataSource table. Presumably in production this wouldn't be happening regularly, only in testing.

**Closed by dclim** 2016-09-19 21:11 UTC
Labels: Bug

**Comment by dclim** [comment] 2016-09-21 23:06
Implemented in #3484

**Comment by himanshug** [comment] 2016-11-08 20:48
@gianm @dclim as discussed in dev-sync, it is beneficial for some users (where data ingestion does not have to have the guarantees of exactly once semantics) to have a configuration option available that does the reset automatically without waiting for manual intervention.
@pjain1 can you please make that happen?

**Comment by pjain1** [comment] 2016-11-10 19:02
PR that enables option automatic offset reset - https://github.com/druid-io/druid/pull/3678
