### ISSUE TITLE
[Discuss] Null handling

### ISSUE THREAD

**Issue by jon-wei** [druid-io/druid#2778] opened 2016-04-02 00:53 UTC
Recently there have been quite a few PRs and issues opened relating to null/empty string handling. 

I have gathered links to these PRs/issues here, if we would like to have a wider discussion on this topic.
#2715 - stringFormat extractionFn should be able to return null on null values (Fix for #2706) #2715
#2737 - Fix predicate-based ValueMatcher behavior for IncrementalIndex on missing columns.
#2758 - handle null values in In Filter
#2765 - Null string is encoded as "null" in incremental index
#2771 - Various ExtractionFn null handling fixes.
#2772 - DimensionPredicateFilter and JavaScriptFilter don't handle null columns properly
#2776 - Inconsistent null/empty str handling for multi-value/single-value dimensions in QueryableIndexStorageAdapter

**Comment by leventov** [comment] 2018-06-02 17:21
Duplicate of #4349

**Closed by leventov** 2018-06-02 17:21 UTC
Labels: Discuss
