### ISSUE TITLE
AnnouncerTest sporadically fails in master in TravisCI

### ISSUE THREAD

**Issue by drcrallen** [druid-io/druid#1393] opened 2015-05-27 13:14 UTC
AnnouncerTest seems to be failing pretty regularly in TravisCI these days.

Specifically `AnnouncerTest.testSessionKilled` will often fail when checking the data in ZK

**Comment by drcrallen** [comment] 2015-05-28 17:26
I looked into this a bit, and it might stem from assumptions of atomicity in the announcer. This was partially addressed in https://github.com/druid-io/druid/pull/1109 but not completely.

Curator does provide a `org.apache.curator.framework.recipes.nodes.PersistentEphemeralNode` which accomplishes exactly what the announcer intends to accomplish, but has two major distinctions:

1. There is no atomicity (all tasks are background tasks)
1. There is no compression like is currently enforced in the Announcer.

The Announcer probably needs re-written using the mechanism in PersistentEphemeralNode or similar.

Additionally, any place which uses the announcer probably needs assumptions of atomicity removed.

**Comment by himanshug** [comment] 2016-01-06 15:43
this is duplicate of #2167

**Closed by himanshug** 2016-01-06 15:43 UTC
Labels: Bug, Difficulty - Hard, Priority - High

**Comment by drcrallen** [comment] 2016-01-06 16:57
wouldn't 2167 be a duplicate of this one?

**Comment by himanshug** [comment] 2016-01-06 16:59
@drcrallen ok, let me rephrase, "this is duplicated by 2167" :)
