### ISSUE TITLE
groupBy regression going from 0.6 to 0.7

### ISSUE THREAD

**Issue by sixtus** [druid-io/druid#1175] opened 2015-03-06 13:54 UTC
"aggregations": [
    { "type": "longSum", "name": "foo", "fieldName": "foo" },
    { "type": "longSum", "name": "foo_bar", "fieldName": "foo_bar" }
  ],
  having{"type": "greaterThan", "aggregation": "foo", "value": 0}

The having makes an aggregation with an _ go 0 (i.e. foo_bar has a value w/o having, but is always 0 if having is added).

This used to work in 0.6 and it still works for aggregations without _ (this might be a coincident)

**Comment by fjy** [comment] 2015-03-06 18:54
@sixtus I created a test case for the behavior you are seeing in https://github.com/druid-io/druid/pull/1176. The test passes and I am so far unable to reproduce the problem. Please make sure the test case is covering the error you are reporting.

I have a sneaking suspicion the root of the problem you are seeing is related to something else, possibly casing. If you remove the having spec, does foo_bar have a value? Does the case of foo_bar match in your data, ingestion spec, and in your query?

**Comment by sixtus** [comment] 2015-03-06 18:58
It's all lower case and it has worked reliably for the last 2 years (it's very old code I was totally surprised to break after upgrading).

I have multiple metrics in my query, they all work fine, except the one with the underscore. Removing the having clause makes 0.7 return correct results.

If you are interested I send you a PM with the true query and results.

**Comment by sixtus** [comment] 2015-03-23 22:46
I am unable to work on this issue atm (we fixed it by using a different query), I am sorry.

Again, if you are interested I send you the true query and response via PM.

**Comment by fjy** [comment] 2015-06-07 18:29
I am closing this as unable to reproduce. Please reopen if it is still an issue

**Closed by fjy** 2015-06-07 18:29 UTC
