### ISSUE TITLE
Move to AWS S3 SDK

### ISSUE THREAD

**Issue by niketh** [druid-io/druid#4289] opened 2017-05-17 20:40 UTC
I plan to move to using AWS S3 SDK instead of using JetS3T. I have noticed the following problems with JetS3T:

1. AWS SDK has better support for auth (reading credentials files etc)
2. It is far behind AWS S3 SDK in terms of development-release/support.

What do you think @gianm @leventov @cheddar ?

**Comment by gianm** [comment] 2017-05-17 20:44
+1, aws-java-sdk seems better than jets3t these days. Related: #4116 which would add support for s3a (aws-java-sdk backed S3) to Hadoop indexing.

**Comment by drcrallen** [comment] 2017-05-17 20:51
There are some in the community who use jets3t.properties, so such a change would either need a migration plan or a major version update

**Comment by gianm** [comment] 2017-05-17 20:53
My feeling is it's not worth supporting both at the same time, and instead we should do it in 0.11.0 and tell people that jets3t properties will no longer be respected (but whatever new aws-java-sdk configurator thing will).

**Comment by drcrallen** [comment] 2017-05-17 21:10
@gianm agreed. also it wasn't clear in my prior message, but I think moving to the AWS sdk is a great idea.

**Comment by leventov** [comment] 2017-05-17 21:18
Duplicate of #3886

**Comment by leventov** [comment] 2017-05-24 20:19
Labelling `Incompatible` and `Release Notes` because present users may have `jets3t.properties` file to change some s3 configurations, that will stop working silently when code is changed to use official SDK.

**Comment by drcrallen** [comment] 2017-05-24 20:20
@leventov is the solution for this one going to have to have a config that creates a https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/index.html?com/amazonaws/ClientConfiguration.html  , or do you know of a way to have a `jets3t.properties` kind of file on the classpath?

**Comment by leventov** [comment] 2017-05-24 20:21
@drcrallen I don't know, but creating a config via "Druid native" properties sounds like a good solution, for unification.

**Comment by leventov** [comment] 2017-06-07 23:25
Related #4382

**Comment by jihoonson** [comment] 2017-12-07 02:23
I'm working on this.

**Comment by sjtoik** [comment] 2017-12-13 08:42
Cool! The endpoint configuration should be trivial with the new AWSClient-builder thingy. That just needs to be propagated trough-out the stack.

**Closed** 2018-03-21 22:36 UTC
Labels: Improvement, Incompatible, Release Notes
