### ISSUE TITLE
[Proposal] Merge multiple Druid source subprojects into fewer projects.

### ISSUE THREAD

**Issue by himanshug** [druid-io/druid#5229] opened 2018-01-07 06:24 UTC
There have been multiple discussions about Druid source having too many sub-projects which really doesn't provide much value and often leads to complications e.g. `server/src/main/java/io/druid/client/indexing/ClientXXXQuery.java` classes are equivalent to `XXXTask.java` classes in `indexing-service/` and needs to stay in sync .. more such classes are created in #5102 .
similar desire has been mentioned in https://github.com/metamx/java-util/pull/74#issuecomment-353473234 and https://github.com/druid-io/druid/pull/5102#discussion_r158430657 .

So, here is my initial idea....

1. merge `druid-api, druid-commons, java-utils, druid-processing` into `druid-core`
2. merge `druid-server, druid-indexing-service` into `druid-server`

we can merge things further if necessary.

**Comment by leventov** [comment] 2018-01-07 07:17
Duplicate of #4312

**Comment by himanshug** [comment] 2018-01-08 23:18
Closing in favor of #4312

**Closed** 2018-01-10 04:55 UTC
