### ISSUE TITLE
Druid Indexing Episode II: Attack of the Columns

### ISSUE THREAD

**Issue by fjy** [druid-io/druid#151] opened 2013-05-17 21:08 UTC
Druid indexing needs to be revisited to improve indexing performance and functional capability. Currently, v8 segments are created by IndexMerger and converted to v9. We should be able to build v9 segments directly.

**Comment by xvrl** [comment] 2015-01-20 18:34
seems to be a duplicate of #55

**Closed** 2015-01-20 19:59 UTC
