### ISSUE TITLE
Investigate IncrementalIndex ValueMatcher performance

### ISSUE THREAD

**Issue by gianm** [druid-io/druid#3799] opened 2016-12-23 19:06 UTC
@leventov raised a concern in review of #3797 that even though IncrementalIndex ValueMatcher benchmarks look fine, this may not hold up in production when different strategy types are mixed. We should endeavor to write a better benchmark that smokes out any potential performance regressions, and if regressions are found, fix them before release of 0.10.0. I think FilteredAggregatorFactory benchmarks are a good place to try to verify this.

See review comment in https://github.com/druid-io/druid/pull/3797#discussion_r93735214 and response in https://github.com/druid-io/druid/pull/3797#discussion_r93792025.

**Comment by leventov** [comment] 2016-12-23 20:08
Shouldn't this issue be called like "Make benchmarks to emulate non-uniformity of production queries"?

However this work will be made obsolete by #3798, because the essence of #3798 is specifically getting rid of megamorphism inside hot query processing loops, that makes production to perform just like mono-query benchmarks. But #3798 almost certainly won't be part of 0.10.0, because it is 10-15 PRs away from completion. And propagating this optimization to types of queries different from topN will take even longer.

And also because adding `DimensionSelector.makeValueMatcher()` is a useful optimization with or without #3798, I suggest to add it before 0.10.0 to ensure there is no performance regression in this area in 0.10.0. While preparing, running and verifying proper benchmarks for 0.10.0 is a lot of work, that will be obsolete soon.

**Comment by gianm** [comment] 2016-12-23 20:17
I think "Make benchmarks to emulate non-uniformity of production queries" is too broad to be a github issue (how would you know when you fully achieved that?) so would prefer to make issues for smaller things where it's clear when they are achieved. It sounds like you are suggesting to _not_ do benchmarks but to just do the optimization anyway, is that right?

Also, could you please write up a proposal about what changes you need to make #3798 work? It seems like whatever changes you are making there are likely to have code conflicts with work that @jon-wei is doing to follow up on #3570, to handle grouping on more types than just strings (bringing even more polymorphism to the query path).

The goal would be to get both of those efforts moving in the same direction.

**Comment by leventov** [comment] 2016-12-23 20:34
Yes, I suggest to not do benchmarks, because this work (very time-consuming) will be obsoleted soon. So yes, I suggest to "blindly" do some optimization before 0.10.0 to have the same level of ValueMatcher specialization we had before #3797.

Definitely there will be some code conflicts between #3798 and #3570 follow-ups, but they are not going to be very big, those works are not contradictory. So either I or @jon-wei will need to rebase, depending on whose work is merged into master first. Adding more polymorphism is not a problem for #3798, because it's job is to turn any level of polymorphism into monomorphism.

**Comment by leventov** [comment] 2016-12-23 20:35
Regarding this optimization, `DimensionSelector.makeValueMatcher()`, I'm ready to do it myself.

**Comment by gianm** [comment] 2016-12-23 20:41
Ok, that'd be helpful. Hopefully the optimization doesn't blow up the code size too badly.

I'd still really like to see at least a sketch of a proposal of #3798 – I'm curious what approach you plan on taking.

**Comment by leventov** [comment] 2016-12-23 21:00
@gianm see https://github.com/druid-io/druid/issues/3798#issuecomment-269045047

**Closed** 2017-01-25 23:28 UTC
Labels: Performance
