### ISSUE TITLE
Total count differed by different dim order

### ISSUE THREAD

**Issue by sundy-li** [druid-io/druid#1825] opened 2015-10-14 07:56 UTC
Hi, I found a bug as follows:

```
 "aggregations": [
    {
      "byRow": true,
      "fieldNames": [
        "dim1",
        "dim2"
      ],
      "name": "totalCount",
      "type": "cardinality"
    }
  ]

```

```
 "aggregations": [
    {
      "byRow": true,
      "fieldNames": [
       "dim2",
       "dim1"
      ],
      "name": "totalCount",
      "type": "cardinality"
    }
  ]

```

That results to different count~

**Comment by sundy-li** [comment] 2015-10-14 07:58
The version of druid is 0.7

**Comment by sundy-li** [comment] 2015-10-14 08:29
I also found the group by these two dim query return larger rows than the count query.

**Comment by drcrallen** [comment] 2015-10-14 14:28
@sundy-li HyperLogLog (the algorithm cardinality uses) is an approximate algorithm. How different are the two cardinality counts?

**Comment by sundy-li** [comment] 2015-10-14 14:31
But I didnot notic it is an  approximate algorithm.  From  what I can see, it is about 2%, which is not accpetable by our company's customers, is it any way to output the accurate count ?

**Comment by nishantmonu51** [comment] 2015-10-14 14:38
@sundy-li you can get an exact count by using nested groupBy query, for this case the inner query will group by the unique column and the outer query will do a count aggregator over the grouped values giving you the exact unique counts. However, please note that this approach will be order of magnitude slower than using cardinality aggregator. you might also need to tune the memory configs for your nodes since the intermediate results for groupby will need to be fetched in memory.

**Comment by drcrallen** [comment] 2015-10-14 14:40
Unfortunately 2% is well within normal error ranges for HLL. Best practices on getting exact counts would be better asked in the user forums at https://groups.google.com/forum/#!forum/druid-user @nishantmonu51 would you mind posting that in the forum thread as well and linking the thread here?

For that sql query, there is no official druid.io sql parser. Please file a new issue and include what the actual query being sent to druid is. (or else it will just get lost in this thread)

Also note https://github.com/druid-io/druid/pull/1632  and https://github.com/druid-io/druid/pull/1781 which are a few very notable groupBy problems encountered recently.

Closing because parent issue is working as intended.

**Closed by drcrallen** 2015-10-14 14:40 UTC

**Comment by drcrallen** [comment] 2015-10-14 14:43
I also have filed https://github.com/druid-io/druid/issues/1826 to make sure the expected behavior is better spelled out in the docs.

**Comment by fjy** [comment] 2015-10-14 17:37
@sundy-li to provide some more explanation. Certain computations such as
count distinct are fundamentally slow operations and no brilliant
architecture can overcome limitations in physics. For this reason, people
have started developing approximate sketch algorithms that can greatly
improve performance and reduce storage. Using an approximate cardinality
algorithm can dramatically reduce the amount of data you have to store and
improve operations over this data by orders of magnitude. The question for
your design is, do you want to store potentially 100x more data and have
queries run 100x slower for 100% accuracy? If so, you can look into
Nishant's suggestion, and also take a look at lexicographic topNs, which
can paginate through the values of a dimension and you can count the number
of values present.

**Comment by sundy-li** [comment] 2015-10-15 02:14
I got that,  thanks for all your explanations and advices
