### ISSUE TITLE
SQL: Selecting certain columns results in an exception

### ISSUE THREAD

**Issue by AlexCharlton** [druid-io/druid#4637] opened 2017-08-02 20:56 UTC
Selecting certain columns from certain SQL queries frequently returns the following error: `Unknown exception: Cannot coerce[java.util.ArrayList] to VARCHAR`

Which columns/queries that are affected seems to be non-deterministic, though I can always make a given query work by excluding particular columns. Eg. for one query, I cannot select column X without having an error returned, but for a different query I cannot select column Y. Sometimes a query can work for some time, and then start failing, despite pulling in the exact same set of data. In the case of this error, the columns in question seem to be always empty (determined by cross-referencing the column/query in question over the JSON query API).

Doing a `select *` very frequently returns this error for me.

**Comment by gianm** [comment] 2017-08-02 22:13
I think this happens with multi-value columns. They aren't totally supported yet.

**Comment by gianm** [comment] 2017-08-02 22:17
See also #4638.

**Comment by AlexCharlton** [comment] 2017-08-04 17:27
Ah, I see. I just realized now that I _have_ only seen this with multi-value columns. Thanks!

**Comment by gianm** [comment] 2017-08-22 17:51
Thanks for confirming -- I'll close this as a duplicate of #4638.

**Closed by gianm** 2017-08-22 17:51 UTC
Labels: Bug
