### ISSUE TITLE
IngestSegmentFirehose not handling partitioned segments properly.

### ISSUE THREAD

**Issue by jowy** [druid-io/druid#1053] opened 2015-01-19 04:47 UTC
All metrics output from the ingest segment firehose end up as, for example: output sum ~= (input sum / input partition count). Looking in to the issue now, but it may be due to IngestSegmentFirehose emitting the partition chunks sequentially and out of chronological order as the indexer expects.

How I believe the IngestSegmentFirehose is emitting:

With partitioned segments:

event index | indexer yield | row timestamp | segment | partition
------------ | ------------ | ------------- | ------------- | -------------
0 | 0 | 20150101T000001 | 20150101T000000/20150101T010000 | 0
3 | 1 | 20150101T000002 | .  .  . | 0
6 | 2 | 20150101T000003 | .  .  . | 0
1 | 3 | ~~20150101T000001~~ | .  .  . | 1
4 | 4 | ~~20150101T000002~~ | .  .  . | 1
7 | 5 | 20150101T000003 | .  .  . | 1
2 | 6 | ~~20150101T000001~~ | .  .  . | 2
5 | 7 | ~~20150101T000002~~ | .  .  . | 2
8 | 8 | 20150101T000003 | .  .  . | 2

With unpartitioned segments:

event index | indexer yield | row timestamp | segment | partition
------------ | ------------ | ------------- | ------------- | -------------
0 | 0 | 20150101T000001 | 20150101T000000/20150101T010000 | 0
1 | 1 | 20150101T000001 | .  .  . | 0
2 | 2 | 20150101T000001 | .  .  . | 0
3 | 3 | 20150101T000002 | .  .  . | 0
4 | 4 | 20150101T000002 | .  .  . | 0
5 | 5 | 20150101T000002 | .  .  . | 0
6 | 6 | 20150101T000003 | .  .  . | 0
7 | 7 | 20150101T000003 | .  .  . | 0
8 | 8 | 20150101T000003 | .  .  . | 0

**Comment by fjy** [comment] 2015-01-19 19:55
Duplicated by #1052

**Comment by fjy** [comment] 2015-01-19 20:36
Keeping this one open as it has more info and closing #1052

**Comment by nishantmonu51** [comment] 2015-01-20 05:08
your observation is correct, IngestSegmentFirehose works by iterating over all the available segments and emmitting the events for each segment or partition one by one, It should be fine to emit the events out of order of timestamps as IndexTask does not place any such restriction on the order of events on the firehose. 

can you explain more on what is the issue that you are facing ?

**Comment by luxuec** [comment] 2015-01-22 09:27
Adding more information:

for my use case, when running index task on a data source that has 36 partitions (partition number 2~37),  
IngestSegmentFirehoseFactory.java throws NPE in places getChunk(0). 
IndexerDBCoordinator.java throws NPE in places getChunk(0).

**Comment by nishantmonu51** [comment] 2015-01-23 14:07
Hi luxuec, can you share the logs with complete stack trace for more detials ?

**Comment by luxuec** [comment] 2015-01-26 08:30
2015-01-26 08:27:30,542 ERROR [task-runner-0] io.druid.indexing.overlord.ThreadPoolTaskRunner - Exception while running task[IndexTask{id=index_pulsar_event_m_2015-01-26T08:22:34.208Z, type=index, dataSource=pulsar_event_m}]
java.lang.NullPointerException
        at io.druid.indexing.firehose.IngestSegmentFirehoseFactory.connect(IngestSegmentFirehoseFactory.java:169)
        at io.druid.indexing.common.task.IndexTask.getDataIntervals(IndexTask.java:237)
        at io.druid.indexing.common.task.IndexTask.run(IndexTask.java:196)
        at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:218)
        at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:197)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
2015-01-26 08:27:30,547 INFO  [task-runner-0] io.druid.indexing.worker.executor.ExecutorLifecycle - Task completed with status: {
  "id" : "index_pulsar_event_m_2015-01-26T08:22:34.208Z",
  "status" : "FAILED",
  "duration" : 215189
}

I am using 0.6.169.

**Comment by luxuec** [comment] 2015-01-27 02:24
2015-01-06 06:42:11,553 WARN  [qtp266612841-143] org.eclipse.jetty.server.HttpChannel - /druid/indexer/v1/action
com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: java.util.HashMap["result"]->com.google.common.collect.TransformingRandomAccessList[0])
at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:232)
at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:211)
at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:210)
at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:105)
at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:21)
at com.fasterxml.jackson.databind.ser.std.AsArraySerializerBase.serialize(AsArraySerializerBase.java:186)
at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:401)
at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:322)
at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:27)
at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:118)
at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:494)
at com.fasterxml.jackson.jaxrs.base.ProviderBase.writeTo(ProviderBase.java:542)
at com.sun.jersey.spi.container.ContainerResponse.write(ContainerResponse.java:306)
at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1479)
at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1391)
at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1381)
at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:416)
at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:538)
at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:716)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:278)
at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:268)
at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:180)
at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:93)
at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:132)
at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:129)
at com.google.inject.servlet.GuiceFilter$Context.call(GuiceFilter.java:206)
at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:129)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
at io.druid.server.http.RedirectFilter.doFilter(RedirectFilter.java:71)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:300)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
at org.eclipse.jetty.server.Server.handle(Server.java:497)
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:620)
at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:540)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
at io.druid.indexing.overlord.IndexerDBCoordinator$2.apply(IndexerDBCoordinator.java:129)
at io.druid.indexing.overlord.IndexerDBCoordinator$2.apply(IndexerDBCoordinator.java:125)
at com.google.common.collect.Lists$TransformingRandomAccessList.get(Lists.java:573)
at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:84)
... 47 more

**Comment by nishantmonu51** [comment] 2015-01-28 06:33
Hi luxec, 
what is the partitionsSpec you are using ? 
why are the partition number starting from 2 ? 
have you manually deleted or modified any partitions entry in mysql ? 
It looks like the NPE might have been caused by not having metadata about all the partitions.

**Comment by luxuec** [comment] 2015-01-28 06:41
This is because I use below shardSpec in real time kafka ingestion,

            "shardSpec": {
                "type": "linear",
                "partitionNum": 2
            }

Also attach Eric's response here:
https://groups.google.com/d/msg/druid-development/k-Q-Rj52czk/AOLtNu0Dr1kJ

**Comment by nishantmonu51** [comment] 2015-06-03 09:23
Fixed by #1190

**Closed by nishantmonu51** 2015-06-03 09:23 UTC
