### ISSUE TITLE
metrics for Query Count statistics always stay ZERO

### ISSUE THREAD

**Issue by QijingLi** [druid-io/druid#4844] opened 2017-09-25 22:26 UTC
We made some queries from Broker, and got the metrics query/time/avg was not Zero, so I expect the all of the following metrics should not be ZERO.

1) query/success/count - number of successful queries
2) query/failed/count - number of failed queries
3) query/interrupted/count - number of interrupted/timedout queries

**Comment by asandulescu** [comment] 2017-10-23 15:54
Running into the same issue. All the query/*/count metrics are ZERO even though  queries are being fired off and can be confirmed by looking at all the other query/* metrics.

**Comment by gianm** [comment] 2017-10-23 16:54
This is due to a bug and should be fixed in the next release (Druid 0.11.0) . Until then, you could count the number of "query/time" metrics -- it should be equivalent to the number of queries made. The "success" dimension will let you differentiate successful from failed queries.

Sorry for the inconvenience.

**Closed by gianm** 2017-10-23 16:54 UTC

**Comment by asandulescu** [comment] 2017-10-24 09:53
Thank you for your response :)

**Comment by Gauravshah** [comment] 2018-08-21 13:40
was this fixed in 0.11.0 ? we are using 0.11.0 and still seeing 0 on count metrics.
cc @ShilpaSivanesan

**Comment by gianm** [comment] 2018-08-21 15:28
I believe it was fixed by #4517 when QueryResource became a singleton again. At least, I'm looking at `query/success/count` on some clusters running 0.12.x versions and they look like they're reporting it OK.

**Comment by Gauravshah** [comment] 2018-08-21 15:34
thank you @gianm
